name: learn-github-actions
on: [push]
jobs:
  install-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      #- run: export SFDX_AUTOUPDATE_DISABLE=false
      #- run: export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
      #- run: export SFDX_DOMAIN_RETRY=300
      #- run: export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true
      #- run: export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true
      #- run: mkdir sfdx
      #- run: wget -qO- $CIURL | tar xJ -C sfdx --strip-components 1
      #  env : 
      #    CIURL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      #- run: "./sfdx/install"
      #- run: export PATH=./sfdx/$(pwd):$PATH
      #- run: sfdx update
      #- run: sfdx --version
      #- run: sfdx plugins --core
      -  run: which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
      -  run: eval $(ssh-agent -s)
      -  run: ssh-add <(echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAoV+KpCUlduWUnpOp7Kw54MgdxarAEChnbXNAO9EL06hOa6zFR+ut
/GYroarPHYmbvCU6gUzB4WBzhNLVKgJqVkHKQV84maWlJLTrGRZagySgobcyIw2NmofYmw
4ARiR0K+oTj7rbqubmwJiO2xtvI4fOEtIbwzG8kQ92inDeMnggIwB1jUs1hnjRBguFWbiv
X6SIYNJV0WUowldqGU9N19V1aMA1lCFAy5JrLXyx0aIQeVLuxVhOGg7Q2LO1TswlXQkqzd
NoQMXRMwIAP/wsTukPkxSucLFVZoS4qOADP9Pt8h0XpP4U04gSpVaPBW0JV16tQswHmQcu
km8dtmDSLISo/qsXMSUeqtIrF2HkypbUeaIMjshHxXTZIQ4Cv/PrakT1dxGP2f61VOEXsB
Uzx0GdPGNSjR9atiD1Tj+22Jri08HRfRx4uQw8NCsNvDtI8I4aMJ1rLp/PjqjIzIYiSZRe
5EaDojcGJkWrD+04iFj2VlZa7kIkkATp1CQg3bGjAAAFmICtZ5aArWeWAAAAB3NzaC1yc2
EAAAGBAKFfiqQlJXbllJ6TqeysOeDIHcWqwBAoZ21zQDvRC9OoTmusxUfrrfxmK6Gqzx2J
m7wlOoFMweFgc4TS1SoCalZBykFfOJmlpSS06xkWWoMkoKG3MiMNjZqH2JsOAEYkdCvqE4
+626rm5sCYjtsbbyOHzhLSG8MxvJEPdopw3jJ4ICMAdY1LNYZ40QYLhVm4r1+kiGDSVdFl
KMJXahlPTdfVdWjANZQhQMuSay18sdGiEHlS7sVYThoO0NiztU7MJV0JKs3TaEDF0TMCAD
/8LE7pD5MUrnCxVWaEuKjgAz/T7fIdF6T+FNOIEqVWjwVtCVderULMB5kHLpJvHbZg0iyE
qP6rFzElHqrSKxdh5MqW1HmiDI7IR8V02SEOAr/z62pE9XcRj9n+tVThF7AVM8dBnTxjUo
0fWrYg9U4/ttia4tPB0X0ceLkMPDQrDbw7SPCOGjCday6fz46oyMyGIkmUXuRGg6I3BiZF
qw/tOIhY9lZWWu5CJJAE6dQkIN2xowAAAAMBAAEAAAGABv4069gQP47DWfvcKT1tZKhHYg
F8QTb/BGcyKWVttcZdX50lD3DPIVjsGx1jzEviS8zxNBk3baTYXLEmO6PPJ93B/gM6WK4s
8eJFLdkiIvy7WUavDYXQ1Rl98Xox2NhLkHucTWYzjrxi04XI6wXNUyTXcUlZmqPVIBQjdu
xdNKKwAdRLQ8w2jZU+uZxWMwUl1Gc04b07qs9PbNyM5HvjS68cX2W07K5kOG4n5ti4e/Uh
8Z/+aN7iw45QzpM7ECcYhcnt7526bTgpzwqQf9UJRymkcdOpTJpVmTsiu4NlDxB/tM2d4z
hzaXpm9oAUGmoR3JgEKPSQqwZQlFrO+GmdGn4w0I1lCk/BuARBQyXqpTVBBfBSVWwcM0d4
r+lqH4IaG4KVmL9pzV+gTRfjj6bkSLCqD9wPEB5OyKvFMHDUGS4sQgFr8YmFFb97m8tEH6
m66fGLe/S1iZqrAhtzmJHVCxQHWZ61qA6IZJ14iil/trd08BkeGLcLt6bLv+IwWOwBAAAA
wQCY+pUNJF/3NmAEqUSgNTvvRdJI+TVDOqtDdmUZjUegULD6vTAX8wBwCiHsjZzNZfDD4U
Qh0CsD1HpHDup/nM9wFy6FTZm7uETBZasSn8m5xfykP7mN72VjJl3zWoayHeiBGN3QDD9f
4AC2VkeIKhqeRGitzjrex0GagheLCLxHquVAOG/xSFrAb+8gIA/hsFWk41l2F7JBcU1xcy
WGF2flwsBNcRlD85Zs7RoNRgMsiZN9YiS1Ryag50NSBKIwx34AAADBAMtlu5ReaJJXJ0J+
Z/VMVWhaKflgbdmKhKwV2y4LZ7a/IgQ8RBzGCYrtBhnr2ES5C6MStUDZz2w8p7BEgA+Euq
nUOOjkzM9ERAiWSzKGml4Rc2fjefKDSpPyYJvuZl0+txzi7XMYY2pjwheGF8CqH3511IEE
wnvVVKMotZHIk2nn34u0VU0NHY6RBeaSMmbyd8Pf7Fe9SOlTVEqQO82W3WKynGhrEOYiPM
w1i+pdd5MHrteDRERcI4R68VQT11Sm4wAAAMEAyxuG4d7R/BScT07+echB+FK321EtGKB8
wZQBqG4n7vryZGJi9frfHvoyrtal8S7rE1Dy30RIE6S0EuXPHoOd/bR3aN2VZ++iaAFZGN
oMIBc0yvPpWVhQLZKy/KQdYlO04Mp+s3oGgYEy/pmtxKaT9iQ8EKG5hC9w5JZeXXSQ3NOx
xy4e5Uqc2r7gMZMYXWkJF12lDvFOaVYpWSW88uhF5skFwrPZ946dzOoojfDvz+TH5WZccq
EY9a24cGJ5kgZBAAAAIWVsbGlvdC5jYXRoZXJpbkBjb21mb3J0aC1rYXJvby5ldQE=
-----END OPENSSH PRIVATE KEY-----
")
      -  run: mkdir -p ~/.ssh
      -  run: chmod 700 ~/.ssh
      -  run: ssh -T git@git.karoo.fr
      -  run: git config --global http.sslverify false
      -  run: git config --global user.name "KAROO CI"
      -  run: git config --global user.email "ci@karoo.fr"
      -  run: git config --global core.quotepath false
      -  run: git remote set-url --push origin "${CI_PROJECT_URL/$FIND/$REPLACE}"
         env : 
          FIND: "https://git.karoo.fr"
          REPLACE: "ssh://git@git.karoo.fr"
      -  run: git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.karoo.fr/".insteadOf https://git.karoo.fr/
              

          


