name: learn-github-actions
on: [push]
jobs:
  install-cli:
    runs-on: ubuntu-latest
    steps:
      - env: CIURL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: export SFDX_AUTOUPDATE_DISABLE=false
      - run: export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
      - run: export SFDX_DOMAIN_RETRY=300
      - run: export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true
      - run: export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true
      - run: mkdir sfdx
      - run: wget -qO- $CIURL | tar xJ -C sfdx --strip-components 1
      - run: "./sfdx/install"
      - run: export PATH=./sfdx/$(pwd):$PATH
      - run: sfdx update
      - run: sfdx --version
      - run: sfdx plugins --core
          


