name: Manage Pull Requests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test-lint:
    name: test-lint
    if: |
      env.CI_ENABLE == 1 &&
      env.DISABLE_LINT != 1 &&
      env.DISABLE_TEST != 1
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY2 }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      CI_ENABLE: ${{ secrets.CI_ENABLE }}
      DISABLE_LINT: ${{ DISABLE_LINT }}
      DISABLE_TEST: ${{ DISABLE_TEST }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Setup
          run: ./scripts/github/before_script.sh
        - name: Lint
          run: |
            cidx source:lint

  test-scan-apex:
    name: test-scan-apex
    if: |
      env.CI_ENABLE == 1 &&
      env.DISABLE_SCAN_TEST != 1 &&
      env.DISABLE_TEST != 1
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY2 }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      CI_ENABLE: ${{ secrets.CI_ENABLE }}
      DISABLE_SCAN_TEST: ${{ secrets.DISABLE_SCAN_TEST }}
      DISABLE_TEST: ${{ secrets.DISABLE_TEST }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/upload-artifact@v2
        with:
          name: test-scan-apex
          path: Artifact/*
      - name: Setup
        run: ./scripts/github/before_script.sh
      - name: Lint
        run: |
          npm install pmd-bin --global --loglevel=error
          cidx source:scan -@

  check_SIT:
    name: check_SIT
    # this job will only run if:
    # - the PR has been created, synchronized or reopened in the 'develop' branch,
    # - CI_ENABLE = true,
    # - DISABLE_SIT = false
    if: |
      contains( github.ref, 'develop') &&
      env.CI_ENABLE == 1 &&
      env.DISABLE_SIT != 1
    needs: [test-lint, test-scan-apex]
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY2 }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      AUTH_SIT_URL: ${{ secrets.AUTH_SIT_URL }}
      CI_UNITTEST_DISABLE: false
      CI_ENABLE: ${{ secrets.CI_ENABLE }}
      DISABLE_SIT: ${{ secrets.DISABLE_SIT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/upload-artifact@v2
        with:
          name: check_SIT
          path: Artifact/*
      - name: Setup
        run: ./scripts/github/before_script.sh
      - name: Deploy to SIT
        run: |
          cidx org:auth --alias=sit --url=${{env.AUTH_SIT_URL}}
          cidx org:deploy --alias=sit --incremental --cleanSequence=deploy.cleanSequence.json --artifact --notest=${{env.CI_UNITTEST_DISABLE}} --checkOnly=true
