name: TestDumpCIDX

on: [workflow_dispatch]
jobs:
  OrgDumpJob:
    # this job will only run if:
    # - the PR has been merged in the 'develop' branch,
    # - CI_ENABLE = true,
    # - DISABLE_SIT = false
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY2 }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      AUTH_SIT_URL: ${{ secrets.AUTH_SIT_URL }}
      CI_UNITTEST_DISABLE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Setup
        run: |
           chmod +x ./scripts/github/before_script.sh && chmod +x ./scripts/github/init_git.sh && chmod +x ./scripts/github/install_salesforce_cli.sh && ./scripts/github/before_script.sh
      - name: Org Dump
        run: |
          cidx org:auth --alias=org --url=${{env.AUTH_SIT_URL}}
          cidx org:dump -@ --alias=org
          CI_SYNC_NAME_full=${CI_SYNC_NAME:-$CI_COMMIT_REF_NAME}