name: TestDumpCIDX

on: [push]
jobs:
  OrgDumpJob:
    # this job will only run if:
    # - the PR has been merged in the 'develop' branch,
    # - CI_ENABLE = true,
    # - DISABLE_SIT = false
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY2 }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      AUTH_SIT_URL: ${{ secrets.AUTH_SIT_URL }}
      CI_UNITTEST_DISABLE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Setup
        run: ./scripts/github/before_script.sh
      - name: Org Dump
        run: |
          cidx org:auth --alias=org --url=${{env.AUTH_SIT_URL}}
          cidx org:dump -@ --alias=org